Temporarily disable forked execution due to Grails' logging conflicts.
When we run grails using grails.project.fork.run=true we get a NoClassDefFoundError
caused by org/apache/commons/beanutils/BeanUtils which is needed by log4j.